import { chromium } from "@playwright/test";
import assert from "node:assert/strict";

const browser = await chromium.launch({ executablePath: process.env.BROWSER_PATH || "/opt/google/chrome/chrome", headless: true, args: ["--no-sandbox", "--use-angle=swiftshader", "--enable-unsafe-swiftshader", "--use-fake-device-for-media-stream", "--use-fake-ui-for-media-stream"] });
const base = process.env.BASE_URL || "http://localhost:3000";
const issues = [];
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1050 }, deviceScaleFactor: 1 });
  const page = await context.newPage(); page.on("pageerror", (error) => issues.push(error.message));
  page.on("console", (message) => { if (message.type() === "error") console.log("Console error:", message.text()); });
  await page.goto(base, { waitUntil: "networkidle", timeout: 60000 });
  await page.locator('.engine-canvas[data-ready="true"]').waitFor({ timeout: 60000 });
  await page.waitForTimeout(1800);
  assert.equal(await page.locator("[data-engine-canvas]").count(), 1);
  await page.screenshot({ path: "/tmp/kinetic-desktop.png", fullPage: true });
  console.log("Rendered engine and desktop screenshot");
  await page.locator('[data-part="head"]').click();
  assert.equal(await page.getByTestId("part-action").isDisabled(), true);
  await page.locator('[data-part="cover"]').click();
  await page.getByTestId("part-action").click();
  assert.match(await page.getByTestId("installed-count").textContent(), /14/);
  await page.getByRole("button", { name: "Simulate", exact: true }).click();
  assert.match(await page.getByRole("status").textContent(), /Reassemble all/);
  for (let i = 0; i < 14; i++) await page.getByRole("button", { name: "Remove next", exact: true }).click();
  assert.equal((await page.getByTestId("installed-count").textContent()).replace(/\s/g, ""), "0/15");
  assert.equal(await page.getByRole("button", { name: "Remove next", exact: true }).isDisabled(), true);
  await page.getByRole("button", { name: "Reassemble all", exact: true }).click();
  await page.waitForFunction(() => document.querySelector('[data-testid="installed-count"]').textContent.replace(/\s/g, "") === "15/15", null, { timeout: 15000 });
  console.log("All 15 assemblies dismantled and reinstalled; dependencies enforced");
  await page.getByRole("button", { name: "Inspect", exact: true }).click();
  await page.getByLabel("Camera angle").selectOption("Bottom");
  await page.waitForTimeout(250);
  await page.getByRole("button", { name: "Zoom in", exact: true }).click();
  await page.getByRole("button", { name: "Zoom out", exact: true }).click();
  await page.getByRole("button", { name: "Reset view", exact: true }).click();
  await page.getByLabel("Toggle exploded view").click();
  await page.waitForTimeout(1500);
  await page.screenshot({ path: "/tmp/kinetic-exploded.png", fullPage: true });
  await page.getByLabel("Toggle exploded view").click();
  await page.getByRole("button", { name: "Cutaway", exact: true }).click();
  await page.getByRole("button", { name: "X-ray", exact: true }).click();
  await page.getByRole("button", { name: "X-ray", exact: true }).click();
  await page.getByRole("button", { name: "Isolate", exact: true }).click();
  await page.getByRole("button", { name: "Show all", exact: true }).click();
  await page.getByRole("button", { name: "Simulate", exact: true }).click();
  const before = await page.getByLabel("Crankshaft angle").inputValue();
  await page.getByRole("button", { name: "Play simulation", exact: true }).click();
  await page.waitForTimeout(900);
  assert.notEqual(await page.getByLabel("Crankshaft angle").inputValue(), before);
  await page.getByRole("button", { name: "Pause simulation", exact: true }).click();
  await page.getByRole("button", { name: "3 Power", exact: true }).click();
  assert.ok(Number(await page.getByLabel("Crankshaft angle").inputValue()) >= 360);
  await page.screenshot({ path: "/tmp/kinetic-cutaway.png", fullPage: true });
  console.log("Camera presets, zoom, explode, isolate, cutaway and motion controls passed");
  await page.getByRole("button", { name: "Enable hand controls", exact: false }).click();
  await page.waitForFunction(() => document.querySelector(".hand-panel")?.getAttribute("data-camera-status") === "ready" || document.querySelector(".camera-error"), null, { timeout: 60000 });
  const cameraError = await page.locator(".camera-error").allTextContents();
  assert.deepEqual(cameraError, [], "Local hand worker must initialize on synthetic webcam");
  await page.waitForTimeout(2000);
  assert.equal(await page.locator(".camera-preview video").evaluate((video) => video.srcObject.getVideoTracks()[0].readyState), "live");
  await page.screenshot({ path: "/tmp/kinetic-camera.png", fullPage: true });
  await page.getByRole("button", { name: "Stop camera", exact: false }).click();
  assert.equal(await page.locator(".camera-preview video").evaluate((video) => video.srcObject), null);
  console.log("Local MediaPipe worker initialized, camera frames processed and stream released");
  // Simulate denied permission without requesting the tester's real camera.
  await page.evaluate(() => { navigator.mediaDevices.getUserMedia = async () => { throw new DOMException("Denied", "NotAllowedError"); }; });
  await page.getByRole("button", { name: "Enable hand controls", exact: false }).click();
  await page.getByRole("alert").filter({ hasText: "Camera permission was denied" }).waitFor();
  await page.getByRole("button", { name: "How it works", exact: false }).click();
  assert.equal(await page.getByRole("dialog").isVisible(), true);
  await page.keyboard.press("Escape");
  assert.equal(await page.getByRole("dialog").isVisible(), false);
  await context.close();

  const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, isMobile: true, hasTouch: true });
  mobile.on("pageerror", (error) => issues.push(error.message));
  await mobile.goto(base, { waitUntil: "networkidle" });
  await mobile.locator('.engine-canvas[data-ready="true"]').waitFor();
  await mobile.waitForTimeout(900);
  assert.equal(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  assert.equal(await mobile.getByRole('button', { name: 'Finger zoom tool', exact: true }).count(), 1);
  const touch = await mobile.context().newCDPSession(mobile);
  await mobile.locator('[data-engine-canvas]').scrollIntoViewIfNeeded();
  const bounds = await mobile.locator('[data-engine-canvas]').boundingBox();
  const mx = bounds.x + bounds.width * .45, my = bounds.y + bounds.height * .5;
  const mobileZoom = async () => Number((await mobile.getByTestId('viewer-zoom').textContent()).replace('%', ''));
  const touchStartZoom = await mobileZoom();
  const points = (gap) => [{ x: mx-gap, y: my, id: 1 }, { x: mx+gap, y: my, id: 2 }];
  await touch.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: points(25) });
  for (const gap of [30,40,50,65]) await touch.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: points(gap) });
  await mobile.waitForTimeout(300);
  const touchCloser = await mobileZoom(); assert.ok(touchCloser > touchStartZoom, 'Spreading two fingers on the viewer zooms in');
  for (const gap of [55,45,35,25]) await touch.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: points(gap) });
  await touch.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
  await mobile.waitForTimeout(300);
  assert.ok(await mobileZoom() < touchCloser, 'Closing two fingers on the viewer zooms out');
  assert.equal(await mobile.evaluate(() => visualViewport.scale), 1, 'Touch zoom changes the engine, not browser page magnification');
  await touch.detach();
  await mobile.getByRole('button', { name:'Reset view', exact:true }).click();
  await mobile.getByLabel("Show components").click();
  await mobile.locator('[data-part="piston"]').click();
  assert.equal(await mobile.getByRole("heading", { name: "Piston & rings" }).isVisible(), true);
  await mobile.screenshot({ path: "/tmp/kinetic-mobile.png", fullPage: true });
  assert.deepEqual(issues, []);
  console.log("Passed: mobile layout, touch zoom in/out, component selection, camera failure feedback, guide dialog; no page errors");
} finally { await browser.close(); }
